# Generated by Django 2.1.1 on 2018-09-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
