# Generated by Django 2.1.1 on 2018-11-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
