# Generated by Django 2.1.1 on 2018-11-12 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20181112_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
