# Generated by Django 2.1.3 on 2018-11-14 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0010_auto_20181112_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_start', models.DateField(default=datetime.date(1900, 1, 1))),
                ('sem_end', models.DateField(default=datetime.date(1900, 1, 1))),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
