# Generated by Django 2.1.3 on 2018-11-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_auto_20181114_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
