# Generated by Django 2.1.3 on 2018-11-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_timetable_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='details',
        ),
    ]
