# Generated by Django 2.1.3 on 2018-11-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_remove_timetable_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='value_int',
            field=models.IntegerField(default=-1),
        ),
    ]
