# Generated by Django 2.1.3 on 2019-01-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_timetable_value_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='percentage',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
