# Generated by Django 2.1.3 on 2019-01-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_subject_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='venue',
            field=models.CharField(default='---', max_length=200),
        ),
    ]
